#!/usr/bin/env bash
file="$1"
if [ $2 = "-l" ]
then
cat "$file" | grep -aPoc 's\0t\0r\0i\0n\0g\0'
fi

i=$(cat "$file" | grep -aPbo 's\0t\0r\0i\0n\0g\0'  | awk -F: '{print $1}' | head -n $1 | tail -1)
o=$(printf "%d\n" "0x$(cat "$file" | head -c $(($i+15)) |tail -c 4 | xxd -p)")
cat "$file" | head -c $((i+15+$o)) | tail -c $o | tr -d '\0'
